ktor:
  application:
    modules:
      - me.pie.ApplicationKt.module
  deployment:
    port: "$PORT:7478"

kyokyoko:
  remote-sources:
    - "https://raw.githubusercontent.com/SauceEnjoyer/htvn/main/remote_url"