name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - uses: actions/upload-artifact@v4
        with:
          name: kyokyoko
          path: ./build/libs/kyokyoko-0.0.1-standalone.jar
          retention-days: 90